name: core
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/powerd6/core
issue_tracker: https://github.com/powerd6/core/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  powerbook: ^1.0.3
  powerd6: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
